model: resnet50

# criterion: crossentropy

class_weight: False    # if you use class weight to calculate cross entropy or not
writer_flag: True      # if you use tensorboardx or not

batch_size: 16
n_classes: 102

width: 224
height: 224

num_workers: 2
max_epoch: 50

optimizer: SGD
scheduler: onplateau

learning_rate: 0.0005
lr_patience: 10       # Patience of LR scheduler
momentum: 0.9         # momentum of SGD
dampening: 0.0        # dampening for momentum of SGD
weight_decay: 0.0001  # weight decay
nesterov: True        # enables Nesterov momentum

path_data: ./datasets/path.txt
data_path: ./datasets
result_path: ./result/cfg1/